Extended Makefile to perform environment check before building.

diff --git a/diss/Makefile b/diss/Makefile
--- a/diss/Makefile
+++ b/diss/Makefile
@@ -1,15 +1,55 @@
-SRCTEX := dissertation.tex
-SRCPDF := $(SRCTEX:.tex=.pdf)
+SRCTEX  := dissertation.tex
+SRCPDF  := $(SRCTEX:.tex=.pdf)
+LATEX   := latex
 LATEXMK := latexmk
+OKAY_TEXLIVE_VERSION := 2016
 
 .PHONY: $(SRCPDF)
-$(SRCPDF):
+$(SRCPDF): check-environment
 	$(LATEXMK) -pdf $(SRCTEX)
 
 .PHONY: clean
 clean:
 	$(LATEXMK) -c $(SRCTEX)
 
-.PHONY=distclean
+.PHONY: distclean
 distclean:
 	$(LATEXMK) -C $(SRCTEX)
+
+.PHONY: check-environment
+check-environment:
+	@echo -n "Checking environment... "
+	@if [ -z `which $(LATEX)` ]; then \
+		echo; \
+		echo "ERROR: $(LATEX) not installed"; \
+		echo; \
+		exit 1; \
+	fi
+	@if [ -z `which $(LATEXMK)` ]; then \
+		echo; \
+		echo "ERROR: $(LATEXMK) not installed"; \
+		echo; \
+		exit 1; \
+	fi
+	@LATEX_VERSION=`$(LATEX) --version | head -n1 | grep "TeX Live"` && \
+	if [ -z "$(TEXLIVECHECK)" ] && [ -z "$$LATEX_VERSION" ]; then \
+		echo; \
+		echo "WARN: Tex Live not installed"; \
+		echo "Set TEXLIVECHECK=false to disable this check."; \
+		echo; \
+		exit 1; \
+	fi && \
+	TEXLIVE_VERSION=`echo "$$LATEX_VERSION" | \
+					 sed 's/.*TeX Live //' | \
+					 sed 's/).*//'` && \
+	if [ -z "$(TEXLIVECHECK)" ] && \
+	   [ $$TEXLIVE_VERSION -lt $(OKAY_TEXLIVE_VERSION) ]; then \
+		echo; \
+		echo -n "WARN: too old Tex Version "; \
+	    echo "(found $$TEXLIVE_VERSION, expected >= $(OKAY_TEXLIVE_VERSION))"; \
+		echo "Set TEXLIVECHECK=false to disable this check."; \
+		echo; \
+		exit 1; \
+	fi
+	@echo "OK"
+
